apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Chart.Name }}-sa"
  namespace: {{ required "A valid .Values.namespace is required!" .Values.namespace }}
  labels: 
    {{- include "nsvalidator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Chart.Name }}-sa-binding"
  labels: 
    {{- include "nsvalidator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-sa"
    namespace: {{ required "A valid .Values.namespace is required!" .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
