apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsvalidator.fullname" . }}
  namespace: {{ required "A valid .Values.namespace is required!" .Values.namespace }}
  labels: 
    {{- include "nsvalidator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: http
  selector: 
    {{- include "nsvalidator.selectorLabels" . | nindent 4 }}
